/* Voz e escuta da NEXO AI usando Web Speech API. */
export interface AoFalar { aoIniciar?: () => void; aoTerminar?: () => void; aoErro?: (motivo: string) => void; aoNivel?: (nivel: number) => void; }
export interface AoOuvir { aoParcial?: (texto: string) => void; aoFinal?: (texto: string) => void; aoErro?: (motivo: string) => void; aoFim?: () => void; }
export interface ProvedorVoz { readonly nome: string; readonly podeFalar: boolean; readonly podeOuvir: boolean; falar(texto: string, cb?: AoFalar): void; pararFala(): void; ouvir(cb?: AoOuvir): void; pararEscuta(): void; }
interface ReconhecimentoFala extends EventTarget { lang: string; continuous: boolean; interimResults: boolean; start(): void; stop(): void; abort(): void; onresult: ((e: { results: ArrayLike<ArrayLike<{ transcript: string }> & { isFinal: boolean }> }) => void) | null; onerror: ((e: { error: string }) => void) | null; onend: (() => void) | null; }
type ConstrutorReconhecimento = new () => ReconhecimentoFala;
function construtorReconhecimento(): ConstrutorReconhecimento | null { if (typeof window === 'undefined') return null; const w = window as unknown as { SpeechRecognition?: ConstrutorReconhecimento; webkitSpeechRecognition?: ConstrutorReconhecimento }; return w.SpeechRecognition ?? w.webkitSpeechRecognition ?? null; }
export function escolherVozFeminina(vozes: SpeechSynthesisVoice[]): SpeechSynthesisVoice | null { if (!vozes.length) return null; const ptBR = vozes.filter((v) => /pt[-_]?BR/i.test(v.lang)); const candidatas = ptBR.length ? ptBR : vozes.filter((v) => /^pt/i.test(v.lang)); const nomes = /(maria|luciana|fernanda|francisca|ana|helena|vit[óo]ria|female|mulher|feminin)/i; return candidatas.find((v) => nomes.test(v.name)) ?? candidatas[0] ?? vozes[0] ?? null; }
class VozNativa implements ProvedorVoz {
 readonly nome = 'navegador'; private reconhecimento: ReconhecimentoFala | null = null; private timerNivel: ReturnType<typeof setInterval> | null = null; private vozCache: SpeechSynthesisVoice | null = null;
 get podeFalar(): boolean { return typeof window !== 'undefined' && 'speechSynthesis' in window; }
 get podeOuvir(): boolean { return construtorReconhecimento() !== null; }
 private resolverVoz(): SpeechSynthesisVoice | null { if (this.vozCache) return this.vozCache; this.vozCache = escolherVozFeminina(window.speechSynthesis.getVoices()); return this.vozCache; }
 falar(texto: string, cb: AoFalar = {}): void { if (!this.podeFalar || !texto.trim()) { cb.aoTerminar?.(); return; } window.speechSynthesis.cancel(); const fala = new SpeechSynthesisUtterance(texto.replace(/[*_~`#]+/g, ' ')); fala.lang = 'pt-BR'; fala.rate = 1.05; fala.pitch = 1.05; const voz = this.resolverVoz(); if (voz) fala.voice = voz; fala.onstart = () => { cb.aoIniciar?.(); this.timerNivel = setInterval(() => cb.aoNivel?.(0.35 + Math.random() * 0.5), 90); }; const encerrar = () => { if (this.timerNivel) clearInterval(this.timerNivel); this.timerNivel = null; cb.aoNivel?.(0); }; fala.onend = () => { encerrar(); cb.aoTerminar?.(); }; fala.onerror = () => { encerrar(); cb.aoErro?.('Falha ao sintetizar a voz.'); }; window.speechSynthesis.speak(fala); }
 pararFala(): void { if (this.podeFalar) window.speechSynthesis.cancel(); if (this.timerNivel) { clearInterval(this.timerNivel); this.timerNivel = null; } }
 ouvir(cb: AoOuvir = {}): void { const Construtor = construtorReconhecimento(); if (!Construtor) { cb.aoErro?.('Este navegador não reconhece voz. Use o teclado.'); return; } this.pararEscuta(); const rec = new Construtor(); rec.lang = 'pt-BR'; rec.continuous = false; rec.interimResults = true; rec.onresult = (e) => { let parcial = ''; let finalizado = ''; for (let i = 0; i < e.results.length; i++) { const r = e.results[i]!; const txt = r[0]?.transcript ?? ''; if (r.isFinal) finalizado += txt; else parcial += txt; } if (parcial) cb.aoParcial?.(parcial); if (finalizado) cb.aoFinal?.(finalizado.trim()); }; rec.onerror = (e) => { const erros: Record<string, string> = { 'not-allowed': 'Permissão de microfone negada.', 'service-not-allowed': 'O serviço de reconhecimento de voz não está disponível neste navegador.', 'no-speech': 'Não ouvi nada. Tente de novo.', 'audio-capture': 'Não foi possível acessar o microfone.', network: 'Erro de rede no reconhecimento de voz.', aborted: 'O reconhecimento de voz foi interrompido.', 'language-not-supported': 'O reconhecimento de português não está disponível neste navegador.' }; cb.aoErro?.(erros[e.error] ?? `Falha no reconhecimento de voz (${e.error}).`); }; rec.onend = () => cb.aoFim?.(); this.reconhecimento = rec; try { rec.start(); } catch { cb.aoErro?.('Não foi possível iniciar a escuta.'); } }
 pararEscuta(): void { if (this.reconhecimento) { try { this.reconhecimento.abort(); } catch {} this.reconhecimento = null; } }
}
export function criarProvedorVoz(): ProvedorVoz { return new VozNativa(); }
